### ISSUE TITLE
【urllib3.exceptions.MaxRetryError】VC発行時にエラーが発生します。

### ISSUE THREAD

**Issue by HarukiKondo** [aws-samples/decentralized-identity-sample#61]
@fsatsuki 

こちらのソースコードと下記ブログ記事を参考に動かしてみようしています。

https://aws.amazon.com/jp/blogs/news/decentralized-identity-sample/

`DeployEnvironment`内の手順に従ってCDKで全てのスタックをデプロイし

holder用、Issuer用、Verifier用のフロントエンドを立ち上げるところまでは上手くいっています。
※ issuer-profile.jsonも見えることを確認しています。

issuer用のフロントエンドからVCを発行しようとしたところ以下のようなエラーが発生しました。

```bash
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=2773): Max retries exceeded with url: /secretsmanager/get?secretId=issuerWebAppSecretIssuerPri-iU9OsFACrX1U (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f540ca2efa0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

こちらですが、 `issue_vc.py` の中で実装している`get_secretmanager`メソッドでのエラーかと思っています。

```python
def get_secretmanager(secret_name):

  url = 'http://localhost:2773'
  header = {'X-Aws-Parameters-Secrets-Token': os.getenv('AWS_SESSION_TOKEN')}
  parameter_encode = requests.utils.quote(secret_name)
  path = f'secretsmanager/get?secretId={parameter_encode}'
  res = requests.get(f'{url}/{path}', headers=header)

  if res.status_code == 200:
      secret = json.loads(res.text)["SecretString"] 
      privateKey = json.loads(secret)['issuer_privatekey']

      # 秘密鍵をファイルに保存
      with open("/tmp/issuer.pk", mode="w") as f:
        f.write(privateKey)

      #return data['Parameter']['Value']
      return None
  else:
      print(
          f"Failed to get SSM parameter store {SSM_ISSUER_PRIVATEKEY_NAME}")
      return None
```

localhost:2773 に接続できないとのことなので何か追加で設定が必要なのでしょうか？？

もしお分かりでしたらご教示いただけますと幸いです。

よろしくお願いいたします。

**Comment by fsatsuki** [comment]
そのコードはSecrets Managerに保存したIssuerのPrivateKeyを取得する箇所です。
構築手順のこちらで実施した `ISSUER_PRIVATEKEY` の値を取得しています。
https://github.com/aws-samples/decentralized-identity-sample/blob/7b63f28a28d3a06403e249c88838cdad6ebd7541/docs/DeployEnvironment/2_DeployIssuerWebApp.md?plain=1#L53-L58

Secrets Managerに接続するLambda LayerをCDKで導入しているため、`localhost:2773`で繋がるようになっています。
https://github.com/aws-samples/decentralized-identity-sample/blob/7b63f28a28d3a06403e249c88838cdad6ebd7541/cdk/lib/resources/IssueBackend.ts#L89-L95

まずはマネジメントコンソールからSecrets Managerを開いていただき、エラーログに記載の `/secretsmanager/get?secretId=issuerWebAppSecretIssuerPri-iU9OsFACrX1U` が存在しているかご確認いただけますでしょうか。

**Comment by HarukiKondo** [comment]
@fsatsuki ご確認いただきありがとうございます。

上記の旨、承知いたしました。確認してみます。

**Comment by HarukiKondo** [comment]
<img width="661" alt="タイトルなし" src="https://github.com/user-attachments/assets/3a3e828f-470d-4060-ac09-00a29c850bff">
<img width="905" alt="タイトルなし2" src="https://github.com/user-attachments/assets/462f5323-5718-4860-9218-1974babe3df1">

返信が遅くなりましたが、SecretManagerのシークレットが存在することなどを確認しました。
コンソールログも追加で出力するようにして確認したところ、シークレットからissuerの秘密鍵の値も取得するところでエラーが起きていたので取得できるように修正したりしてみました。

シークレットの取得部分は突破できたので次に進みたいと思います。

ありがとうございました。
